In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#paramètre d'affichage
pd.set_option('display.max_columns', None)
sns.set(style="whitegrid")

#Chargement du dataset principal

file_path = "../data/full_data_flightdelay.csv"
df = pd.read_csv(file_path)

#Aperçu des donnée

print("Dimensions du dataset")
df.head()

Dimensions du dataset

,MONTH,DAY_OF_WEEK,DEP_DEL15,DEP_TIME_BLK,DISTANCE_GROUP,SEGMENT_NUMBER,CONCURRENT_FLIGHTS,NUMBER_OF_SEATS,CARRIER_NAME,AIRPORT_FLIGHTS_MONTH,AIRLINE_FLIGHTS_MONTH,AIRLINE_AIRPORT_FLIGHTS_MONTH,AVG_MONTHLY_PASS_AIRPORT,AVG_MONTHLY_PASS_AIRLINE,FLT_ATTENDANTS_PER_PASS,GROUND_SERV_PER_PASS,PLANE_AGE,DEPARTING_AIRPORT,LATITUDE,LONGITUDE,PREVIOUS_AIRPORT,PRCP,SNOW,SNWD,TMAX,AWND
0,1,7,0,0800-0859,2,1,25,143,Southwest Airlines Co.,13056,107363,5873,1903352,13382999,0.000062,0.000099,8,McCarran International,36.08,-115.152,NONE,0.0,0.0,0.0,65.0,2.91
1,1,7,0,0700-0759,7,1,29,191,Delta Air Lines Inc.,13056,73508,1174,1903352,12460183,0.000144,0.000149,3,McCarran International,36.08,-115.152,NONE,0.0,0.0,0.0,65.0,2.91
2,1,7,0,0600-0659,7,1,27,199,Delta Air Lines Inc.,13056,73508,1174,1903352,12460183,0.000144,0.000149,18,McCarran International,36.08,-115.152,NONE,0.0,0.0,0.0,65.0,2.91
3,1,7,0,0600-0659,9,1,27,180,Delta Air Lines Inc.,13056,73508,1174,1903352,12460183,0.000144,0.000149,2,McCarran International,36.08,-115.152,NONE,0.0,0.0,0.0,65.0,2.91
4,1,7,0,0001-0559,7,1,10,182,Spirit Air Lines,13056,15023,1257,1903352,2688839,0.000009,0.000125,1,McCarran International,36.08,-115.152,NONE,0.0,0.0,0.0,65.0,2.91

In [3]:
#Information générales

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6489062 entries, 0 to 6489061
Data columns (total 26 columns):
 #   Column                         Dtype
---  ------                         -----
 0   MONTH                          int64
 1   DAY_OF_WEEK                    int64
 2   DEP_DEL15                      int64
 3   DEP_TIME_BLK                   object
 4   DISTANCE_GROUP                 int64
 5   SEGMENT_NUMBER                 int64
 6   CONCURRENT_FLIGHTS             int64
 7   NUMBER_OF_SEATS                int64
 8   CARRIER_NAME                   object
 9   AIRPORT_FLIGHTS_MONTH          int64
 10  AIRLINE_FLIGHTS_MONTH          int64
 11  AIRLINE_AIRPORT_FLIGHTS_MONTH  int64
 12  AVG_MONTHLY_PASS_AIRPORT       int64
 13  AVG_MONTHLY_PASS_AIRLINE       int64
 14  FLT_ATTENDANTS_PER_PASS        float64
 15  GROUND_SERV_PER_PASS           float64
 16  PLANE_AGE                      int64
 17  DEPARTING_AIRPORT              object
 18  LATITUDE                       float64
 19  LONGITUDE                      float64
 20  PREVIOUS_AIRPORT               object
 21  PRCP                           float64
 22  SNOW                           float64
 23  SNWD                           float64
 24  TMAX                           float64
 25  AWND                           float64
dtypes: float64(9), int64(13), object(4)
memory usage: 1.3+ GB

In [5]:
# Noms des colonnes

print(df.columns.tolist())

['MONTH', 'DAY_OF_WEEK', 'DEP_DEL15', 'DEP_TIME_BLK', 'DISTANCE_GROUP', 'SEGMENT_NUMBER', 'CONCURRENT_FLIGHTS', 'NUMBER_OF_SEATS', 'CARRIER_NAME', 'AIRPORT_FLIGHTS_MONTH', 'AIRLINE_FLIGHTS_MONTH', 'AIRLINE_AIRPORT_FLIGHTS_MONTH', 'AVG_MONTHLY_PASS_AIRPORT', 'AVG_MONTHLY_PASS_AIRLINE', 'FLT_ATTENDANTS_PER_PASS', 'GROUND_SERV_PER_PASS', 'PLANE_AGE', 'DEPARTING_AIRPORT', 'LATITUDE', 'LONGITUDE', 'PREVIOUS_AIRPORT', 'PRCP', 'SNOW', 'SNWD', 'TMAX', 'AWND']

In [6]:
#Statistiques de base

display(df.describe())

#valeurs manquantes

print("Valeurs manquantes par colunnes :")
print(df.isnull().sum)

,MONTH,DAY_OF_WEEK,DEP_DEL15,DISTANCE_GROUP,SEGMENT_NUMBER,CONCURRENT_FLIGHTS,NUMBER_OF_SEATS,AIRPORT_FLIGHTS_MONTH,AIRLINE_FLIGHTS_MONTH,AIRLINE_AIRPORT_FLIGHTS_MONTH,AVG_MONTHLY_PASS_AIRPORT,AVG_MONTHLY_PASS_AIRLINE,FLT_ATTENDANTS_PER_PASS,GROUND_SERV_PER_PASS,PLANE_AGE,LATITUDE,LONGITUDE,PRCP,SNOW,SNWD,TMAX,AWND
count,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06
mean,6.607062e+00,3.935598e+00,1.891441e-01,3.821102e+00,3.046890e+00,2.783675e+01,1.337397e+02,1.268458e+04,6.296058e+04,3.459251e+03,1.588639e+06,7.814970e+06,9.753707e-05,1.355612e-04,1.153211e+01,3.670581e+01,-9.425515e+01,1.037063e-01,3.159310e-02,9.152397e-02,7.146846e+01,8.341329e+00
std,3.396853e+00,1.995200e+00,3.916231e-01,2.382233e+00,1.757864e+00,2.151060e+01,4.645213e+01,8.839796e+03,3.438223e+04,4.251139e+03,1.123847e+06,5.046882e+06,8.644459e-05,4.649970e-05,6.935706e+00,5.500804e+00,1.790952e+01,3.432134e-01,3.170163e-01,7.281285e-01,1.835333e+01,3.607604e+00
min,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,4.400000e+01,1.100000e+03,5.582000e+03,1.000000e+00,7.047600e+04,4.737940e+05,0.000000e+00,7.134695e-06,0.000000e+00,1.844000e+01,-1.593460e+02,0.000000e+00,0.000000e+00,0.000000e+00,-1.000000e+01,0.000000e+00
25%,4.000000e+00,2.000000e+00,0.000000e+00,2.000000e+00,2.000000e+00,1.100000e+01,9.000000e+01,5.345000e+03,2.503400e+04,6.540000e+02,6.732210e+05,2.688839e+06,3.419267e-05,9.889412e-05,5.000000e+00,3.343600e+01,-1.063770e+02,0.000000e+00,0.000000e+00,0.000000e+00,5.900000e+01,5.820000e+00
50%,7.000000e+00,4.000000e+00,0.000000e+00,3.000000e+00,3.000000e+00,2.300000e+01,1.430000e+02,1.156200e+04,7.087800e+04,2.251000e+03,1.486066e+06,8.501631e+06,6.178236e-05,1.246511e-04,1.200000e+01,3.750500e+01,-8.790600e+01,0.000000e+00,0.000000e+00,0.000000e+00,7.400000e+01,7.830000e+00
75%,1.000000e+01,6.000000e+00,0.000000e+00,5.000000e+00,4.000000e+00,3.900000e+01,1.720000e+02,1.761500e+04,8.631200e+04,4.806000e+03,2.006675e+06,1.246018e+07,1.441659e-04,1.772872e-04,1.700000e+01,4.077900e+01,-8.093600e+01,2.000000e-02,0.000000e+00,0.000000e+00,8.600000e+01,1.029000e+01
max,1.200000e+01,7.000000e+00,1.000000e+00,1.100000e+01,1.500000e+01,1.090000e+02,3.370000e+02,3.525600e+04,1.177280e+05,2.183700e+04,4.365661e+06,1.338300e+07,3.484077e-04,2.289855e-04,3.200000e+01,6.116900e+01,-6.600200e+01,1.163000e+01,1.720000e+01,2.520000e+01,1.150000e+02,3.378000e+01

Valeurs manquantes par colunnes :
<bound method DataFrame.sum of          MONTH  DAY_OF_WEEK  DEP_DEL15  DEP_TIME_BLK  DISTANCE_GROUP  \
0        False        False      False         False           False
1        False        False      False         False           False
2        False        False      False         False           False
3        False        False      False         False           False
4        False        False      False         False           False
...        ...          ...        ...           ...             ...
6489057  False        False      False         False           False
6489058  False        False      False         False           False
6489059  False        False      False         False           False
6489060  False        False      False         False           False
6489061  False        False      False         False           False

         SEGMENT_NUMBER  CONCURRENT_FLIGHTS  NUMBER_OF_SEATS  CARRIER_NAME  \
0                 False               False            False         False
1                 False               False            False         False
2                 False               False            False         False
3                 False               False            False         False
4                 False               False            False         False
...                 ...                 ...              ...           ...
6489057           False               False            False         False
6489058           False               False            False         False
6489059           False               False            False         False
6489060           False               False            False         False
6489061           False               False            False         False

         AIRPORT_FLIGHTS_MONTH  AIRLINE_FLIGHTS_MONTH  \
0                        False                  False
1                        False                  False
2                        False                  False
3                        False                  False
4                        False                  False
...                        ...                    ...
6489057                  False                  False
6489058                  False                  False
6489059                  False                  False
6489060                  False                  False
6489061                  False                  False

         AIRLINE_AIRPORT_FLIGHTS_MONTH  AVG_MONTHLY_PASS_AIRPORT  \
0                                False                     False
1                                False                     False
2                                False                     False
3                                False                     False
4                                False                     False
...                                ...                       ...
6489057                          False                     False
6489058                          False                     False
6489059                          False                     False
6489060                          False                     False
6489061                          False                     False

         AVG_MONTHLY_PASS_AIRLINE  FLT_ATTENDANTS_PER_PASS  \
0                           False                    False
1                           False                    False
2                           False                    False
3                           False                    False
4                           False                    False
...                           ...                      ...
6489057                     False                    False
6489058                     False                    False
6489059                     False                    False
6489060                     False                    False
6489061                     False                    False

         GROUND_SERV_PER_PASS  PLANE_AGE  DEPARTING_AIRPORT  LATITUDE  \
0                       False      False              False     False
1                       False      False              False     False
2                       False      False              False     False
3                       False      False              False     False
4                       False      False              False     False
...                       ...        ...                ...       ...
6489057                 False      False              False     False
6489058                 False      False              False     False
6489059                 False      False              False     False
6489060                 False      False              False     False
6489061                 False      False              False     False

         LONGITUDE  PREVIOUS_AIRPORT   PRCP   SNOW   SNWD   TMAX   AWND
0            False             False  False  False  False  False  False
1            False             False  False  False  False  False  False
2            False             False  False  False  False  False  False
3            False             False  False  False  False  False  False
4            False             False  False  False  False  False  False
...            ...               ...    ...    ...    ...    ...    ...
6489057      False             False  False  False  False  False  False
6489058      False             False  False  False  False  False  False
6489059      False             False  False  False  False  False  False
6489060      False             False  False  False  False  False  False
6489061      False             False  False  False  False  False  False

[6489062 rows x 26 columns]>

In [7]:
# Vérifier les valeurs manquantes
# Va afficher le nombre de valeurs manquantes par colonnes
df.isnull().sum().sort_values(ascending=False)

MONTH                            0
DAY_OF_WEEK                      0
DEP_DEL15                        0
DEP_TIME_BLK                     0
DISTANCE_GROUP                   0
SEGMENT_NUMBER                   0
CONCURRENT_FLIGHTS               0
NUMBER_OF_SEATS                  0
CARRIER_NAME                     0
AIRPORT_FLIGHTS_MONTH            0
AIRLINE_FLIGHTS_MONTH            0
AIRLINE_AIRPORT_FLIGHTS_MONTH    0
AVG_MONTHLY_PASS_AIRPORT         0
AVG_MONTHLY_PASS_AIRLINE         0
FLT_ATTENDANTS_PER_PASS          0
GROUND_SERV_PER_PASS             0
PLANE_AGE                        0
DEPARTING_AIRPORT                0
LATITUDE                         0
LONGITUDE                        0
PREVIOUS_AIRPORT                 0
PRCP                             0
SNOW                             0
SNWD                             0
TMAX                             0
AWND                             0
dtype: int64

In [8]:
df.describe()
#Aperçu statistique global
#Un résumé statistique des colonnes numériques (moyenne, min, max, etc.).

,MONTH,DAY_OF_WEEK,DEP_DEL15,DISTANCE_GROUP,SEGMENT_NUMBER,CONCURRENT_FLIGHTS,NUMBER_OF_SEATS,AIRPORT_FLIGHTS_MONTH,AIRLINE_FLIGHTS_MONTH,AIRLINE_AIRPORT_FLIGHTS_MONTH,AVG_MONTHLY_PASS_AIRPORT,AVG_MONTHLY_PASS_AIRLINE,FLT_ATTENDANTS_PER_PASS,GROUND_SERV_PER_PASS,PLANE_AGE,LATITUDE,LONGITUDE,PRCP,SNOW,SNWD,TMAX,AWND
count,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06,6.489062e+06
mean,6.607062e+00,3.935598e+00,1.891441e-01,3.821102e+00,3.046890e+00,2.783675e+01,1.337397e+02,1.268458e+04,6.296058e+04,3.459251e+03,1.588639e+06,7.814970e+06,9.753707e-05,1.355612e-04,1.153211e+01,3.670581e+01,-9.425515e+01,1.037063e-01,3.159310e-02,9.152397e-02,7.146846e+01,8.341329e+00
std,3.396853e+00,1.995200e+00,3.916231e-01,2.382233e+00,1.757864e+00,2.151060e+01,4.645213e+01,8.839796e+03,3.438223e+04,4.251139e+03,1.123847e+06,5.046882e+06,8.644459e-05,4.649970e-05,6.935706e+00,5.500804e+00,1.790952e+01,3.432134e-01,3.170163e-01,7.281285e-01,1.835333e+01,3.607604e+00
min,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,4.400000e+01,1.100000e+03,5.582000e+03,1.000000e+00,7.047600e+04,4.737940e+05,0.000000e+00,7.134695e-06,0.000000e+00,1.844000e+01,-1.593460e+02,0.000000e+00,0.000000e+00,0.000000e+00,-1.000000e+01,0.000000e+00
25%,4.000000e+00,2.000000e+00,0.000000e+00,2.000000e+00,2.000000e+00,1.100000e+01,9.000000e+01,5.345000e+03,2.503400e+04,6.540000e+02,6.732210e+05,2.688839e+06,3.419267e-05,9.889412e-05,5.000000e+00,3.343600e+01,-1.063770e+02,0.000000e+00,0.000000e+00,0.000000e+00,5.900000e+01,5.820000e+00
50%,7.000000e+00,4.000000e+00,0.000000e+00,3.000000e+00,3.000000e+00,2.300000e+01,1.430000e+02,1.156200e+04,7.087800e+04,2.251000e+03,1.486066e+06,8.501631e+06,6.178236e-05,1.246511e-04,1.200000e+01,3.750500e+01,-8.790600e+01,0.000000e+00,0.000000e+00,0.000000e+00,7.400000e+01,7.830000e+00
75%,1.000000e+01,6.000000e+00,0.000000e+00,5.000000e+00,4.000000e+00,3.900000e+01,1.720000e+02,1.761500e+04,8.631200e+04,4.806000e+03,2.006675e+06,1.246018e+07,1.441659e-04,1.772872e-04,1.700000e+01,4.077900e+01,-8.093600e+01,2.000000e-02,0.000000e+00,0.000000e+00,8.600000e+01,1.029000e+01
max,1.200000e+01,7.000000e+00,1.000000e+00,1.100000e+01,1.500000e+01,1.090000e+02,3.370000e+02,3.525600e+04,1.177280e+05,2.183700e+04,4.365661e+06,1.338300e+07,3.484077e-04,2.289855e-04,3.200000e+01,6.116900e+01,-6.600200e+01,1.163000e+01,1.720000e+01,2.520000e+01,1.150000e+02,3.378000e+01

In [9]:
#Affiche les 10 compagnies aériennes les plus fréquentes

df['CARRIER_NAME'].value_counts().head(10)

CARRIER_NAME
Southwest Airlines Co.          1296329
Delta Air Lines Inc.             938346
American Airlines Inc.           903640
United Air Lines Inc.            601044
SkyWest Airlines Inc.            584204
Midwest Airline, Inc.            300154
JetBlue Airways                  269596
Alaska Airlines Inc.             239337
American Eagle Airlines Inc.     228792
Comair Inc.                      219324
Name: count, dtype: int64

In [11]:
#Les aéreports les plus actifs

df['DEPARTING_AIRPORT'].value_counts().head(10)

DEPARTING_AIRPORT
Atlanta Municipal                   392603
Chicago O'Hare International        329045
Dallas Fort Worth Regional          296449
Stapleton International             247175
Douglas Municipal                   231855
Los Angeles International           217120
Houston Intercontinental            177108
Phoenix Sky Harbor International    172969
San Francisco International         167270
LaGuardia                           166709
Name: count, dtype: int64

In [13]:
#Donne le pourcentage de vols retardés (1 = retard ≥ 15 min, 0 = à l’heure).

df['DEP_DEL15'].value_counts(normalize=True) * 200

DEP_DEL15
0    162.171174
1     37.828826
Name: proportion, dtype: float64

In [14]:
#Moyenne de retard par compagnie (compagnie avec plus des retars).

df.groupby('CARRIER_NAME')['DEP_DEL15'].mean().sort_values(ascending = False).head(10)

CARRIER_NAME
Frontier Airlines Inc.         0.260904
JetBlue Airways                0.254010
Atlantic Southeast Airlines    0.232260
Southwest Airlines Co.         0.209269
American Airlines Inc.         0.200688
United Air Lines Inc.          0.195440
Comair Inc.                    0.194630
Mesa Airlines Inc.             0.194398
Allegiant Air                  0.189324
Spirit Air Lines               0.187864
Name: DEP_DEL15, dtype: float64